<template>
  <section>
    <div class="container">
      <table>
        <thead>
          <tr>
            <td>Name</td>
            <td>Age</td>
            <td>Role</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Ivan</td>
            <td>31</td>
            <td>Designer</td>
          </tr>
          <tr>
            <td>Vlad</td>
            <td>38</td>
            <td>Designer</td>
          </tr>
          <tr>
            <td>Nikita</td>
            <td>28</td>
            <td>Designer</td>
          </tr>
        </tbody>
      </table>
    </div>
  </section>
</template>